"""add user credentials to mqtt settings

Revision ID: 0d5574d55732
Revises: af72d5aff27a
Create Date: 2026-06-21 20:36:49.988130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0d5574d55732"
down_revision: Union[str, Sequence[str], None] = "af72d5aff27a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _insert_setting_if_missing(key: str, value: str = "") -> None:
    connection = op.get_bind()
    connection.execute(
        sa.text(
            """
            INSERT INTO settings (key, value)
            SELECT :key, :value
            WHERE NOT EXISTS (
                SELECT 1 FROM settings WHERE key = :key
            )
            """
        ),
        {"key": key, "value": value},
    )


def upgrade() -> None:
    """Add MQTT credential settings.

    Settings are stored as key/value rows, so no table or column change is
    required. The previous autogenerated migration tried to alter SQLite column
    types on unrelated tables, which SQLite does not support. Keep this migration
    focused and idempotent.
    """
    _insert_setting_if_missing("mqtt_username", "")
    _insert_setting_if_missing("mqtt_password", "")


def downgrade() -> None:
    """Remove MQTT credential settings."""
    op.get_bind().execute(
        sa.text(
            "DELETE FROM settings WHERE key IN ('mqtt_username', 'mqtt_password')"
        )
    )
