"""add core models

Revision ID: 40fe710f11a2
Revises: d97f5fa1f223
Create Date: 2026-06-20 17:42:01.637361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40fe710f11a2'
down_revision: Union[str, Sequence[str], None] = 'd97f5fa1f223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_names() -> set[str]:
    return set(sa.inspect(op.get_bind()).get_table_names())


def _indexes(table_name: str) -> set[str]:
    inspector = sa.inspect(op.get_bind())
    if table_name not in inspector.get_table_names():
        return set()
    return {index["name"] for index in inspector.get_indexes(table_name)}


def upgrade() -> None:
    """Upgrade schema.

    Be idempotent for prototype SQLite databases that were already initialized
    by app startup code before Alembic versioning existed.
    """
    tables = _table_names()
    if "events" not in tables:
        op.create_table('events',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('source', sa.String(length=100), nullable=False),
        sa.Column('plugin', sa.String(length=100), nullable=False),
        sa.Column('event_type', sa.String(length=50), nullable=False),
        sa.Column('ip', sa.String(length=64), nullable=True),
        sa.Column('country', sa.String(length=8), nullable=True),
        sa.Column('hostname', sa.String(length=255), nullable=True),
        sa.Column('status_code', sa.Integer(), nullable=True),
        sa.Column('path', sa.String(), nullable=True),
        sa.Column('severity', sa.String(), nullable=False),
        sa.Column('data_json', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    if op.f('ix_events_ip') not in _indexes("events"):
        op.create_index(op.f('ix_events_ip'), 'events', ['ip'], unique=False)
    if "systems" not in tables:
        op.create_table('systems',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('vmid', sa.String(), nullable=False),
        sa.Column('hostname', sa.String(), nullable=False),
        sa.Column('system_type', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    if "assets" not in tables:
        op.create_table('assets',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('system_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('version', sa.String(), nullable=False),
        sa.Column('latest_version', sa.String(), nullable=True),
        sa.Column('release_url', sa.String(), nullable=True),
        sa.Column('update_available', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ),
        sa.PrimaryKeyConstraint('id')
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assets')
    op.drop_table('systems')
    op.drop_index(op.f('ix_events_ip'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
