"""add asset active state

Revision ID: e2ae67a5ba6c
Revises: 40fe710f11a2
Create Date: 2026-06-20 21:15:44.845966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2ae67a5ba6c'
down_revision: Union[str, Sequence[str], None] = '40fe710f11a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assets",
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("1"),
        ),
    )

    op.add_column(
        "assets",
        sa.Column(
            "last_seen",
            sa.DateTime(),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'last_seen')
    op.drop_column('assets', 'is_active')
    # ### end Alembic commands ###
