"""add asset active state

Revision ID: e2ae67a5ba6c
Revises: 40fe710f11a2
Create Date: 2026-06-20 21:15:44.845966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2ae67a5ba6c'
down_revision: Union[str, Sequence[str], None] = '40fe710f11a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _columns(table_name: str) -> set[str]:
    inspector = sa.inspect(op.get_bind())
    if table_name not in inspector.get_table_names():
        return set()
    return {column["name"] for column in inspector.get_columns(table_name)}


def upgrade() -> None:
    """Upgrade schema.

    Be idempotent for prototype SQLite databases that were already initialized
    by app startup code before Alembic versioning existed.
    """
    columns = _columns("assets")
    if "is_active" not in columns:
        op.add_column(
            "assets",
            sa.Column(
                "is_active",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("1"),
            ),
        )

    if "last_seen" not in columns:
        op.add_column(
            "assets",
            sa.Column(
                "last_seen",
                sa.DateTime(),
                nullable=True,
            ),
        )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'last_seen')
    op.drop_column('assets', 'is_active')
    # ### end Alembic commands ###
